#!/usr/bin/env node
// generate-pdf.mjs — Generate PDF from the assembled wallet SDK reference
//
// Uses Puppeteer to render Markdown → HTML → PDF

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';
import { createRequire } from 'module';

// Resolve packages from workspace/node_modules even when script runs from /app/tools
const require = createRequire(join(process.cwd(), 'node_modules', '.package-lock.json'));

const DOCS_DIR = process.env.DOCS_DIR || '/app/docs';
const ARTIFACTS_DIR = join(DOCS_DIR, '..', 'artifacts', 'pdf');

async function main() {
  const { marked } = require('marked');
  const puppeteer = require('puppeteer');

  const mdPath = join(DOCS_DIR, 'wallet-sdk-reference.md');
  const markdown = readFileSync(mdPath, 'utf-8');

  // Convert markdown to HTML
  const htmlBody = marked.parse(markdown);

  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {
    font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
    font-size: 11pt;
    line-height: 1.5;
    max-width: 800px;
    margin: 0 auto;
    padding: 40px 20px;
    color: #1a1a1a;
  }
  h1 { font-size: 24pt; border-bottom: 2px solid #333; padding-bottom: 8px; }
  h2 { font-size: 18pt; border-bottom: 1px solid #ccc; padding-bottom: 4px; margin-top: 30px; }
  h3 { font-size: 14pt; margin-top: 24px; }
  h4 { font-size: 12pt; margin-top: 20px; }
  code {
    background: #f5f5f5;
    padding: 1px 4px;
    border-radius: 3px;
    font-size: 10pt;
  }
  pre {
    background: #f5f5f5;
    padding: 12px;
    border-radius: 6px;
    overflow-x: auto;
    font-size: 9pt;
    line-height: 1.4;
  }
  pre code { background: none; padding: 0; }
  table {
    border-collapse: collapse;
    width: 100%;
    margin: 12px 0;
    font-size: 10pt;
  }
  th, td {
    border: 1px solid #ddd;
    padding: 6px 10px;
    text-align: left;
  }
  th { background: #f0f0f0; font-weight: 600; }
  tr:nth-child(even) { background: #fafafa; }
  .evidence-badge {
    display: inline-block;
    background: #28a745;
    color: white;
    padding: 2px 6px;
    border-radius: 3px;
    font-size: 9pt;
  }
  @media print {
    body { font-size: 10pt; }
    h1 { page-break-before: avoid; }
    h2 { page-break-before: always; }
    table { page-break-inside: avoid; }
  }
</style>
</head>
<body>
${htmlBody}
<footer style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ccc; font-size: 9pt; color: #666;">
  Generated by Aletheia Documentation System.
  Every claim backed by deterministically produced evidence.
</footer>
</body>
</html>`;

  // Generate PDF
  mkdirSync(ARTIFACTS_DIR, { recursive: true });

  const browser = await puppeteer.default.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  });

  const page = await browser.newPage();
  await page.setContent(html, { waitUntil: 'networkidle0' });

  const pdfPath = join(ARTIFACTS_DIR, 'wallet-sdk-reference.pdf');
  await page.pdf({
    path: pdfPath,
    format: 'A4',
    margin: { top: '25mm', right: '20mm', bottom: '25mm', left: '20mm' },
    printBackground: true,
    displayHeaderFooter: true,
    headerTemplate: '<div></div>',
    footerTemplate: '<div style="font-size:8pt;text-align:center;width:100%;color:#999;">Midnight Wallet SDK Reference — Page <span class="pageNumber"></span> of <span class="totalPages"></span></div>',
  });

  await browser.close();
  console.log(`PDF generated: ${pdfPath}`);
}

main().catch(err => {
  console.error('PDF generation failed:', err);
  process.exit(1);
});
